stages:
- build
- test
- publish
- cleanup
- deploy


build_image:
  tags:
    - docker
  stage: build
  script:
    - docker build -t docker.nico-hessler.de/ex/wustopia:$CI_COMMIT_REF_NAME .

test_image:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm docker.nico-hessler.de/ex/wustopia:$CI_COMMIT_REF_NAME python3 tests.py

publish:
  tags:
    - docker
  stage: publish
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.nico-hessler.de
    - docker push docker.nico-hessler.de/ex/wustopia:$CI_COMMIT_REF_NAME


cleanup:
  tags:
    - docker
  stage: cleanup
  except:
    - master
  script:
    - docker rmi docker.nico-hessler.de/ex/wustopia:$CI_COMMIT_REF_NAME

deploy_job:
  tags:
    - docker
  only:
    - master
  stage: deploy
  when: manual
  script:
    - git push github HEAD:master
    - docker tag docker.nico-hessler.de/ex/wustopia:master docker.nico-hessler.de/ex/wustopia:latest
    - docker service update --force wustopia_web
