stages:
- build
- test
- deploy


build_image:
  tags:
    - docker
  stage: build
  script:
    - docker build -t exmatrikulator/wustopia:$CI_COMMIT_REF_NAME .

test_image:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm exmatrikulator/wustopia:$CI_COMMIT_REF_NAME python3 tests.py

deploy_job:
  tags:
    - docker
  only:
    - master
  stage: deploy
  when: manual
  script:
    - docker tag exmatrikulator/wustopia:master exmatrikulator/wustopia:latest
    - docker service update --force wustopia_web
