stages:
- build
- test
- cleanup
- deploy


build_image:
  tags:
    - docker
  stage: build
  script:
    - docker build -t exmatrikulator/wustopia:$CI_COMMIT_REF_NAME .

test_image:
  tags:
    - docker
  stage: test
  script:
    - docker run --rm exmatrikulator/wustopia:$CI_COMMIT_REF_NAME python3 tests.py

cleanup:
  tags:
    - docker
  stage: cleanup
  except:
    - master
  script:
    - docker rmi exmatrikulator/wustopia:$CI_COMMIT_REF_NAME

deploy_job:
  tags:
    - docker
  only:
    - master
  stage: deploy
  when: manual
  script:
    - git remote add github git@github.com:devtal-de/wustopia.git
    - git push github master
    - docker tag exmatrikulator/wustopia:master exmatrikulator/wustopia:latest
    - docker service update --force wustopia_web
