version: '2'
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
  web:
    build: .
    image: exmatrikulator/wustopia
    volumes:
      - config:/app/config
      - migrations:/app/migrations
      #- .:/app
    depends_on:
      - db
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  config:
  data:
  migrations:
